name: Sentinel

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        cd tests/
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        cd ..
    - name: Run test suites
      run: |
        ./run_tests.sh --url ${{ secrets.APIURLDEV }}
